<?php

/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

/**
 * Class Home
 * @package Neoan3\Components
 */

class Home extends Unicore{
    /**
     * Route: home
     */
    function init(): void
    {
        $this
            ->uni('Alpine')
            ->hook('main', 'home', $this->tabsAndContent())
            ->output();
    }
    function tabsAndContent()
    {
        return [
            'tabs' => [
                ['title'=>'first tab', 'content'=> 'content one'],
                ['title'=>'second tab', 'content'=> 'content two'],
                ['title'=>'third tab', 'content'=> '<img src="'.base.'asset/neoan-favicon.png">']
            ]
        ];
    }
}